import os
import time

print ('Assalamualaikum wr wb/')
time.sleep(0.7)
os.system('clear')
print ('')
time.sleep(0.7)
os.system('clear')
print ('Selamat Datang/')
time.sleep(0.7)
os.system('clear')
print ('Di Linux Os|')
time.sleep(0.7)
os.system('clear')
print ('V.7.0/')
time.sleep(0.7)
os.system('clear')
print ('Di Buat Tanggal |')
time.sleep(0.7)
os.system('clear')
print ('30-7-2018/')
time.sleep(0.7)
os.system('clear')
print ('Oleh|')
time.sleep(0.7)
os.system('clear')
print ('BENGKULU CYBER TEAM/')
time.sleep(0.7)
os.system('clear')
print ('CODE BY RISKIS7|')
time.sleep(0.7)
os.system('clear')
print ('Dibuat Untuk Memajukan Bengkulu/')
time.sleep(0.7)
os.system('clear')
print ('Anti Korupsi|')
time.sleep(0.7)
os.system('clear')
print ('Satu Tujuhan/')
time.sleep(0.7)
os.system('clear')
print ('Tidak Berperang Antar Golongan|')
time.sleep(0.7)
os.system('clear')
print ('Tau Teknologi/')
time.sleep(0.7)
os.system('clear')
print ('Tidak Gaptek|')
time.sleep(0.7)
os.system('clear')
print ('Membuat Robot/')
time.sleep(0.7)
os.system('clear')
print ('IG:@Riskis77|')
time.sleep(0.7)
os.system('clear')
print ('YT:BENGKULU CYBER TEAM/')
time.sleep(0.7)
os.system('clear')

